### ISSUE TITLE
EH-16  Module parse failure

### ISSUE THREAD

**Issue by ifoi** [ifoi/edishub#17]
@RoodzFernando    Please look at this code ..   It is giving me the following error   ( i am sure it is something simple that i am missing )

"

./components/collections/CollectionItem
Module parse failed: Unexpected token (25:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         //   </tr> 
|     return (
>         <div> 
|               
|         <h3> Container for list of collections </h3>
  "
  #EH-16   here is a link to the code  https://github.com/ifoi/edishub/blob/feature/collections/components/collections/CollectionItem

**Comment by RoodzFernando** [comment]
### Fixed!

Reason: The proper file extension was missing.
